/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import accesoArchivo.FileHandler;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import problema.*;

/**
 *
 * @author Gabriel
 */
public class GUIPersona extends javax.swing.JFrame implements ActionListener {
    
    //private DefaultListModel<String> model;
    private DefaultListModel<Persona> model;

    public GUIPersona() {
        this.model = new DefaultListModel<>();
        initComponents();
        jBAgregarPersona.addActionListener(this);
        jBEliminar.addActionListener(this);
        jBMostrarDatos.addActionListener(this);
        jBAgregarEstudiante.addActionListener(this);
        jBModificar.addActionListener(this);
        GestorPersonas gest = new GestorPersonas();
        setList(gest.getDatosArchivo());
    }

    /**
     * Creates new form GUIPersona
     */
    //protected ArrayList<Persona> personas;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<Persona>(model);
        jBAgregarPersona = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBMostrarDatos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBAgregarEstudiante = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jBAgregarPersona.setText("<html> \tAgregar<br> \tPersona</html");

        jBEliminar.setText("Eliminar");

        jBMostrarDatos.setText("<html> \tMostrar<br> \tDatos </html");

        jBAgregarEstudiante.setText("<html> \tAgregar<br> \tEstudiante </html");

        jBModificar.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAgregarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAgregarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminar)
                    .addComponent(jBMostrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBModificar))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jBModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAgregarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAgregarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBEliminar)
                .addGap(18, 18, 18)
                .addComponent(jBMostrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 109, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPersona().setVisible(true);
            }
        });
    }

    public void setList(ArrayList<Persona> per) {
        //personas = per;
        model.clear();
        for (Persona p : per) {
            model.addElement(p);
        }
    }

    /*public javax.swing.JList<String> getList(){
        return this.jList1;
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarEstudiante;
    protected javax.swing.JButton jBAgregarPersona;
    protected javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    protected javax.swing.JButton jBMostrarDatos;
    protected javax.swing.JList<Persona> jList1;
    protected javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        GestorPersonas gest = new GestorPersonas();

        if (e.getSource() == jBAgregarPersona) {
            Persona aux = gest.agregarPersona();
            if (aux != null) {
                ((DefaultListModel) jList1.getModel()).addElement(aux);
            }

        } else if (e.getSource() == jBAgregarEstudiante) {
            Estudiante est = gest.agregarEstudiante();
            if (est != null) {
                ((DefaultListModel) jList1.getModel()).addElement(est);
            }
        } else if (e.getSource() == jBEliminar) {
            Persona selectedPersona = model.getElementAt(jList1.getSelectedIndex());
            gest.removePersona(selectedPersona);
            model.removeElement(selectedPersona);
        } else if (e.getSource() == jBMostrarDatos) {
            Persona aux = model.getElementAt(jList1.getSelectedIndex());
            JOptionPane.showMessageDialog(rootPane, "La persona tienes estos datos: \n"
                    + aux.toString1());
        } else if (e.getSource() == jBModificar) {
            int selected = jList1.getSelectedIndex();
            if (model.getElementAt(selected).getClass() == Persona.class) {
                Persona aux = gest.modificarPersona(selected);
                if (aux != null) {
                    ((DefaultListModel) jList1.getModel()).remove(selected);
                    ((DefaultListModel) jList1.getModel()).add(selected, aux);
                }
            } else {
                Estudiante aux = gest.modificarEstudiante(selected);
                if (aux != null) {
                    ((DefaultListModel) jList1.getModel()).remove(selected);
                    ((DefaultListModel) jList1.getModel()).add(selected, aux);
                }
            }
        }
        gest.setDatosArchivo();
    }
}
